language: node_js
install: true

after_success:
    - mv integration/deploy.key.gpg .
    - gpg --yes --batch --passphrase=${DEPLOY_KEY_PASSWORD} deploy.key.gpg
    - chmod 600 deployer.key
    - mv deployer.key ~/.ssh
    - ssh-keyscan ${DEPLOY_SSH_HOST} >> ~/.ssh/known_hosts

    - echo "Host deploy" >> ~/.ssh/config
    - echo "  HostName ${DEPLOY_SSH_HOST}" >> ~/.ssh/config
    - echo "  User ${DEPLOY_SSH_USER}" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/deployer.key" >> ~/.ssh/config

    - cat ~/.ssh/config
    - cat ~/.ssh/deployer.key

    - git remote add deploy ssh://deploy/~/git/rockparade-frontend
    - git push deploy
