language: node_js
install: true

after_success:
    - eval "$(ssh-agent -s)" # start the ssh agent
    - mv integration/deploy.key.gpg .
    - gpg --yes --batch --passphrase=${DEPLOY_KEY_PASSWORD} deploy.key.gpg
    - chmod 600 deployer.key
    - ssh-add deployer.key
    - git remote add deploy ssh://${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}/~/git/rockparade-frontend
    - git push deploy
