language: node_js
install: true

after_success:
    - mv integration/deploy.key.gpg .
    - gpg --yes --batch --passphrase=${DEPLOY_KEY_PASSWORD} deploy.key.gpg
    - chmod 600 deploy.key
    - mv deploy.key ~/.ssh
    - ssh-keyscan ${DEPLOY_SSH_HOST} >> ~/.ssh/known_hosts

    - echo "Host deploy" >> ~/.ssh/config
    - echo "  HostName ${DEPLOY_SSH_HOST}" >> ~/.ssh/config
    - echo "  User ${DEPLOY_SSH_USER}" >> ~/.ssh/config
    - echo "  IdentityFile ~/.ssh/deploy.key" >> ~/.ssh/config

    - git config --global push.default simple
    - git remote add deploy ssh://deploy/~/git/rockparade-frontend
    - git fetch --unshallow || true
    - git fetch origin "+refs/heads/*:refs/remotes/origin/*"
    - git push deploy master

notifications:
    slack: rockparade:IxVBagXvchm7GgEPukl71YTu
