language: node_js
install: true

after_success:
    - eval "$(ssh-agent -s)" # start the ssh agent
    - echo ${SSH_KEY} > deployer.key
    - chmod 600 deployer.key
    - ssh-add deployer.key
    - git remote add deploy ssh://${DEPLOY_SSH_USER}@${DEPLOY_SSH_HOST}/~/git/rockparade-frontend
    - git push deploy
